### ISSUE TITLE
[Question] Any strong reason on using Python 3.11 instead of a lower version?

### ISSUE THREAD

**Issue by lacebal** [thevgergroup/fs-encrypted#6]
Would you mind configuring the tooling to support older versions of Python (3.9)? From a quick glance I don't see why the library should not work with Python 3.9

From Python versions status page https://devguide.python.org/versions/; v3.9 will be supported until next year (2025-Oct)

**Comment by pjaol** [comment]
Sure was just default on my system

**Comment by pjaol** [comment]
@lacebal try now, sorry i didn't see the notification until now

**Comment by pjaol** [comment]
closing as completed
